db:
  host: localhost
  port: 3306
  username: root
  password: r@@00oot
  db_name: smswords_project

stats:
  counting_field: links_found
  flush_threshold: 50

phone_number:
  flush_threshold: 50

schedule:
  sleep_time: 7d

proxy:
  sleep_time: [5s, 10s]

sites:
  example_com:
    disabled: true
    proxy:
      sleep_time: [10, 20s]
    schedule:
      sleep_time: 5d
